CC = cc
CFLAGS = -Wall -Wpedantic -ansi -Wextra -g3 -fsanitize=address

s2_16: 2_16.c
	$(CC) $(CFLAGS) 2_16.c -o s2_16

s2_17: 2_17.c
	$(CC) $(CFLAGS) 2_17.c -o s2_17

s2_18: 2_18.c
	$(CC) $(CFLAGS) 2_18.c -o s2_18

s2_19: 2_19.c
	$(CC) $(CFLAGS) 2_19.c -o s2_19

s2_20: 2_20.c
	$(CC) $(CFLAGS) 2_20.c -o s2_20

s2_22: 2_22.c
	$(CC) $(CFLAGS) 2_22.c -o s2_22

s2_23: 2_23.c
	$(CC) $(CFLAGS) 2_23.c -o s2_23

s2_25: 2_25.c
	$(CC) $(CFLAGS) 2_25.c -o s2_25

s2_26: 2_26.c
	$(CC) $(CFLAGS) 2_26.c -o s2_26

s2_27: 2_27.c
	$(CC) $(CFLAGS) 2_27.c -o s2_27

s2_28: 2_28.c
	$(CC) $(CFLAGS) 2_28.c -o s2_28

s2_29: 2_29.c
	$(CC) $(CFLAGS) 2_29.c -o s2_29

clean:
	rm -f s2_16 s2_17 s2_18 s2_19 s2_20 s2_22 s2_23 s2_25 s2_26 s2_27 s2_28 s2_29
