CC = cc
CFLAGS = -Wall -Wpedantic -ansi -Wextra -g3 -fsanitize=address -lm
fname = temp

# Creates a template file.
temp:
	echo "#include <stdio.h>\n\nint main(void) {\n\treturn 0;\n}" > $(fname).c

s3_16: 3_16.c
	$(CC) $(CFLAGS) 3_16.c -o s3_16

s3_17: 3_17.c
	$(CC) $(CFLAGS) 3_17.c -o s3_17

s3_18: 3_18.c
	$(CC) $(CFLAGS) 3_18.c -o s3_18

s3_19: 3_19.c
	$(CC) $(CFLAGS) 3_19.c -o s3_19

s3_20: 3_20.c
	$(CC) $(CFLAGS) 3_20.c -o s3_20

s3_21: 3_21.c
	$(CC) $(CFLAGS) 3_21.c -o s3_21

s3_22: 3_22.c
	$(CC) $(CFLAGS) 3_22.c -o s3_22

s3_23: 3_23.c
	$(CC) $(CFLAGS) 3_23.c -o s3_23

s3_24: 3_24.c
	$(CC) $(CFLAGS) 3_24.c -o s3_24

s3_25: 3_25.c
	$(CC) $(CFLAGS) 3_25.c -o s3_25

s3_26: 3_26.c
	$(CC) $(CFLAGS) 3_26.c -o s3_26

s3_27: 3_27.c
	$(CC) $(CFLAGS) 3_27.c -o s3_27

s3_32: 3_32.c
	$(CC) $(CFLAGS) 3_32.c -o s3_32

s3_33: 3_33.c
	$(CC) $(CFLAGS) 3_33.c -o s3_33

s3_34: 3_34.c
	$(CC) $(CFLAGS) 3_34.c -o s3_34

s3_35: 3_35.c
	$(CC) $(CFLAGS) 3_35.c -o s3_35

s3_36: 3_36.c
	$(CC) $(CFLAGS) 3_36.c -o s3_36

s3_37: 3_37.c
	$(CC) $(CFLAGS) 3_37.c -o s3_37

s3_38: 3_38.c
	$(CC) $(CFLAGS) 3_38.c -o s3_38

s3_39: 3_39.c
	$(CC) $(CFLAGS) 3_39.c -o s3_39

s3_40: 3_40.c
	$(CC) $(CFLAGS) 3_40.c -o s3_40

s3_41: 3_41.c
	$(CC) $(CFLAGS) 3_41.c -o s3_41

s3_45: 3_45.c
	$(CC) $(CFLAGS) 3_45.c -o s3_45

clean:
	rm -f s3_16 s3_17 s3_18 s3_19 s3_20 s3_21  s3_22 s3_23 s3_24 s3_25 s3_26 s3_27 s3_32 s3_34 s3_35 s3_36 s3_37 s3_38 s3_39 s3_40 s3_41 s3_45
